# External interface to reach the outside world
EXT_INTERFACE: eth0
EXT_NET_NAME: ext-net
EXT_BRIDGE: br-ex
EXT_SUBNET_NAME: ext-subnet
EXT_FLOATING_IP_START: 172.17.0.10
EXT_FLOATING_IP_END: 172.17.254.254
EXT_NETWORK_GATEWAY: 172.17.0.1
EXT_NETWORK_CIDR: 172.17.0.0/16

# Tunnel interface
TUN_INTERFACE: eth0

# Demo tenant name
DEMO_NET_NAME: demo-net
DEMO_SUBNET_NAME: demo-subnet
DEMO_GATEWAY: 172.18.0.1
DEMO_CIDR: 172.18.0.0/16
DEMO_ROUTER: demo-router

database_host: database
