- name: cinder service node packages
  apt: 
    pkg: "{{ item }}" 
    state: "installed"
    force: yes
  tags: packages
  with_items:
    - lvm2
    - cinder-volume

- name: Make sure xvdb is unmounted
  shell: umount -l /dev/xvdb
  ignore_errors: true

# the pv for cinder-volumes is hardcoded to /dev/xvdb right now
- name: get if pv exists for xvdb
  shell: pvs | grep xvdb
  ignore_errors: true
  register: is_xvdb_pv_exist

- name: create xvdb pv
  shell: pvcreate /dev/xvdb
  when: is_xvdb_pv_exist.stdout == ''

- name: get if cinder-volumes vg exists
  shell: vgs | grep cinder-volumes
  ignore_errors: true
  register: is_cinder_volumes_vg_exist

- name: create cinder-volumes vg
  shell: vgcreate cinder-volumes /dev/xvdb
  when: is_cinder_volumes_vg_exist.stdout == ''

- name: write lvm2 configuration
  template: 
    src: lvm.conf.j2 
    dest: /etc/lvm/lvm.conf 
    owner: root 
    group: root
    mode: 0644

- name: create cinder.conf
  template: 
    src: cinder.conf.j2 
    dest: /etc/cinder/cinder.conf 
    owner: root 
    group: root 
    mode: 0644
  notify:
    - restart cinder-volume
    - restart tgt
