- name: restart cinder-scheduler
  service: name=cinder-scheduler state=restarted

- name: restart cinder-api
  service: name=cinder-api state=restarted
  
- name: restart cinder-all
  service: name={{ item }} state=restarted
  with_items:
    - cinder-scheduler
    - cinder-api
