---
- hosts: controller
  haproxy:
    ha_pxc: true
    ha_controller: true  
  user: ubuntu
  roles:
    - haproxy
    - controller_keystone
    - controller_glance
    - controller_cinder
    - controller_nova
    - controller_neutron
    - controller_heat
    - controller_dashboard
