---
# file: site.yml

# A noop to trigger fact collection
- hosts: all
  tasks:
    - name: gtfo
      file: path=/etc/hosts state=touch
    - name: apt-get update
      apt: update_cache=yes
    - name: apt-get upgrade
      apt: upgrade=yes state=latest

- include: common.yml
- include: pxc_bootstrap.yml
- include: pxc_node.yml
- include: controller_rabbitmq.yml
- include: controller_keystone.yml
- include: controller_glance.yml
- include: compute_init.yml
- include: network_init.yml
- include: controller_nova.yml
- include: compute_nova.yml
- include: controller_neutron.yml
- include: compute_neutron.yml
- include: network_neutron.yml
- include: initial_networks.yml
- include: controller_dashboard.yml
- include: controller_cinder.yml
- include: service_cinder.yml
- include: controller_heat.yml
- include: rally_node.yml
