---
# file: site.yml

- hosts: all
  user: ubuntu
  roles:
    - common
  tasks:
    - name: gtfo
      file: path=/etc/hosts state=touch

- include: pxc_bootstrap.yml
- include: pxc_node.yml
- include: queue.yml
- include: init_controller.yml
- include: controller.yml
- include: network.yml
- include: compute.yml
- include: rally_node.yml
