- name: install heat packages
  apt: pkg={{ item }} state=installed
  with_items:
  - heat-api 
  - heat-api-cfn 
  - heat-engine

- name: remove old sqlite db file
  file: path=/var/lib/heat/heat.sqlite state=absent

- name: generate heat configugration
  template: src=heat.conf.j2 dest=/etc/heat/heat.conf owner=root group=root mode=0644
  notify: heat-all

- name: heat db sync
  shell: su -s /bin/sh -c "heat-manage db_sync" heat

- name: create heat service user
  keystone_user: tenant=service user=heat email="heat@localhost" password={{ HEAT_PASS }} login_user=admin login_tenant_name=admin login_password={{ KEYSTONE_ADMIN_PASS }}

- name: add role to heat service user
  keystone_user: tenant=service role=admin user=heat login_user=admin login_tenant_name=admin login_password={{ KEYSTONE_ADMIN_PASS }}
