---

- name: keystone packages
  apt: pkg={{ item }} state=installed
  tags: keystone
  with_items:
    - python-mysqldb
    - keystone
    - python-keystone

- name: write the keystone config file
  template: src=keystone.conf.j2 dest=/etc/keystone/keystone.conf owner=root group=root mode=0644
  notify:
    - restart keystone

- name: install WSGI application shared file
  template: src=keystone.py dest=/usr/share/openstack/keystone/httpd/keystone.py owner=root group=root mode=0644 

# The Keystone Icehouse packages distribute an httpd/keystone.py
# file that must be symlinked to a "main" and an "admin" file that
# is used by the Apache mod_wsgi configuration to load appropriate
# applications from the /etc/keystone/keystone-paste.ini file.
- name: ensure WSGI application main container files written
  file: dest=/var/www/main src=/usr/share/openstack/keystone/httpd/keystone.py state=link owner=root group=root mode=0644
  
- name: ensure WSGI application admin container files written
  file: dest=/var/www/admin src=/usr/share/openstack/keystone/httpd/keystone.py state=link owner=root group=root mode=0644

- name: remove old sqlite db file
  file: path=/var/lib/keystone/keystone.db state=absent

- name: keystone db_sync
  shell: su -s /bin/sh -c "keystone-manage db_sync" keystone

- name: install keystone apache site
  template: src=keystone-site.j2 dest=/etc/apache2/sites-available/keystone.conf owner=root group=root mode=0644

- name: enable keystone site in apache
  shell: a2ensite keystone
  when: keystone_use_apache

- name: disable keystone site in apache (using keystone standalone worker processes)
  shell: a2dissite keystone
  when: not keystone_use_apache

- name: restart apache
  service:
    name: apache2
    state: restarted
  when: keystone_use_apache

- name: restart keystone
  service:
    name: keystone
    state: restarted
  when: not keystone_use_apache

- name: sleep a bit
  shell: sleep 5
  
- name: cron job to flush the old tokens
  cron: name="keystone_flush" user=keystone state=present minute=1 job="/usr/bin/keystone-manage token_flush >/var/log/keystone/keystone-tokenflush.log 2>&1"

- name: render keystone init template
  template: src=keystone_init.sh.j2 dest=/var/tmp/keystone_init.sh owner=root group=root mode=0755

# This creates the Keystone admin tenant, role and user, and all the service endpoints
- name: initialize keystone
  shell: /var/tmp/keystone_init.sh

- name: creates the openstack_admin.rc
  template: src=openstack_admin.rc.j2 dest=/root/.openstack_admin.rc owner=root group=root mode=0600

- name: creates the openstack_demo.rc
  template: src=openstack_demo.rc.j2 dest=/root/.openstack_demo.rc owner=root group=root mode=0600

- name: create service tenant
  keystone_user: tenant=service tenant_description="Service tenant" login_user=admin login_tenant_name=admin login_password={{ KEYSTONE_ADMIN_PASS }}

- name: create demo tenant
  keystone_user: tenant=demo tenant_description="Demo tenant" login_user=admin login_tenant_name=admin login_password={{ KEYSTONE_ADMIN_PASS }}

- name: create demo user
  keystone_user: tenant=demo role="_member_" user=demo password="demo" email="demo@example.com" login_user=admin login_tenant_name=admin login_password={{ KEYSTONE_ADMIN_PASS }}
