- name: cinder controller node packages
  apt: pkg={{ item }} state=installed
  tags: packages
  with_items:
    - cinder-api
    - cinder-scheduler

- name: write the cinder config file
  template: src=cinder.conf.j2 dest=/etc/cinder/cinder.conf owner=root group=root mode=0644
  notify: restart cinder-all

- name: cinder db sync
  shell: su -s /bin/sh -c "cinder-manage db sync" cinder

- name: create cinder service user
  keystone_user: tenant=service user=cinder email="cinder@localhost" password={{ CINDER_PASS }} login_user=admin login_tenant_name=admin login_password={{ KEYSTONE_ADMIN_PASS }}

- name: add role to cinder service user
  keystone_user: tenant=service role=admin user=cinder login_user=admin login_tenant_name=admin login_password={{ KEYSTONE_ADMIN_PASS }}
