- name: cinder controller node packages
  apt: 
    pkg: "{{ item }}" 
    state: installed
    force: yes
  tags: packages
  with_items:
    - cinder-api
    - cinder-scheduler

- name: write the cinder config file
  template: 
    src: cinder.conf.j2 
    dest: /etc/cinder/cinder.conf 
    owner: root 
    group: root 
    mode: 0644
  notify: restart cinder-all

- name: cinder db sync
  shell: su -s /bin/sh -c "cinder-manage db sync" cinder
  when: db_init is defined

- service: 
    name: cinder-api 
    state: restarted

- service: 
    name: cinder-scheduler 
    state: restarted
