- name: RabbitMQ package
  apt: 
    pkg: rabbitmq-server 
    state: installed
    force: yes
  
- name: Start rabbitmq-server
  service: 
    name: rabbitmq-server 
    state: started 
    enabled: true
  
- name: RabbitMQ | Set guest password
  shell: rabbitmqctl change_password guest {{ RABBIT_PASS }}

