- name: Mysql | Set root password
  shell: cat 'mysql-server mysql-server/root_password password {{ MYSQL_ROOT_PASS }}' | debconf-set-selections 

- name: Mysql | Set root repassword
  shell: cat 'mysql-server mysql-server/root_password_again {{ MYSQL_ROOT_PASS }}' | debconf-set-selections

- name: write the mysql config file
  template: 
    src: my.cnf-pxc.j2 
    dest: /etc/mysql/my.cnf 
    owner: root 
    group: root 
    mode: 0644

- name: xtradb cluster package
  apt: 
    pkg: percona-xtradb-cluster-server-5.6 
    state: installed
  
- name: Start Percona server
  service: 
    name: mysql 
    state: started 
    enabled: true

- name: remove anonymous user
  mysql_user: 
    name: ''
    state: absent
