- name: Provison VPC
  local_action:
    module: ec2_vpc
    state: present
    cidr_block: 10.10.0.0/16
    resource_tags: { "Environment":"Load Test" }
    internet_gateway: True
    subnets:
      - cidr: 10.10.10.0/24
        az: "{{ aws_region }}c"
    route_tables:
      - subnets:
          - 10.10.10.0/24
        routes:
          - dest: 0.0.0.0/0
            gw: igw
    region: "{{ aws_region }}"
    wait: yes
  register: vpc

- name: Provision SG
  local_action:
    module: ec2_group
    state: present
    name: "loadtest"
    description: "allow ssh"
    vpc_id: "{{ vpc.vpc_id }}"
    region: "{{ aws_region }}"
    rules:
      - proto: tcp
        from_port: 22
        to_port: 22
        cidr_ip: 0.0.0.0/0

- name: Provision EC2 instances 
  local_action:
    module: ec2
    region: "{{ aws_region }}"
    keypair: "{{ aws_keypair }}"
    group: "loadtest"
    instance_type: "{{ aws_instanceType }}"
    image: "{{ aws_image }}"
    instance_tags:
      role: openstack-host
    exact_count: 4
    count_tag:
      role: openstack-host
    vpc_subnet_id: "{{ vpc.subnets[0].id }}"
    assign_public_ip: True
    wait: yes
  register: id

- debug: var=vpc
