---
# file: roles/common/tasks/main.yml

- name: percona apt key
  apt_key: 
    id: 1C4CBDCDCD2EFD2A 
    url: 'http://www.percona.com/redir/downloads/RPM-GPG-KEY-percona' 
    state: present

- name: percona apt repository binary
  apt_repository: 
    repo: 'deb http://repo.percona.com/apt trusty main' 
    state: present

- name: percona apt repository src
  apt_repository: 
    repo: 'deb-src http://repo.percona.com/apt trusty main' 
    state: present

- name: generate hosts file
  template:
    src: hosts.j2
    dest: /etc/hosts
    owner: root
    group: root
    mode: 0644

# All passwords
- include_vars: group_vars/openstack_password.yml

# Site variables
- include_vars: group_vars/site_def.yml
- include_vars: group_vars/additional_ssh_keys.yml

- name: install packages
  apt:
    pkg: "{{ item }}"
    state: installed
  with_items:
    - python-software-properties
    - ntp
    - sysstat

- name: start and enable ntp
  service: 
    name: ntp 
    state: running 
    enabled: yes

- name: add additional ssh keys
  lineinfile:
    dest: /home/ubuntu/.ssh/authorized_keys
    line: "{{ item }}"
    state: present
  with_items: additional_ssh_keys

- name: install cloud archives key
  apt:
    pkg: ubuntu-cloud-keyring
    state: installed
  when: openstack_release == "juno"

- name: juno apt repository
  template:
    src: juno_apt.j2
    dest: /etc/apt/sources.list.d/ubuntu-cloud-archive-juno-trusty.list
    owner: root
    group: root
    mode: 0644
  when: openstack_release == "juno"

- name: run apt-get update after juno repo is added
  shell: apt-get update
  when: openstack_release == "juno"